---
name: CI

on:
  workflow_dispatch:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ghc: ["9.2.5"]
        stack: ["2.9.3"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Haskell Stack
        uses: haskell/actions/setup@v1.2
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Install dependencies
        run: |
          stack --no-terminal build --system-ghc --pedantic --flag mkjson:-static --test --only-dependencies

      - name: Build
        run: |
          stack --no-terminal build --system-ghc --pedantic --flag mkjson:-static

      - name: Test
        run: |
          stack --no-terminal test --system-ghc --pedantic --flag mkjson:-static
